package component

import (
	"github.com/SCB-SCREAM/oh-my-claude/internal/detect"
)

func init() {
	register(Component{
		ID:          "claude-md",
		Title:       "CLAUDE.md",
		Description: "Project guide Claude reads on every session — common commands, conventions, gotchas.",
		Category:    CategoryClaudeMD,
		Conflict:    ConflictSkipIfExists,
		Files: []TargetFile{{
			Path: "CLAUDE.md",
			Mode: 0o644,
			Body: placeholderBody(
				"# Project guide for Claude Code\n\n" +
					"Replace this file with the project-specific guide M6 will render.\n",
			),
		}},
	})

	register(Component{
		ID:          "settings",
		Title:       ".claude/settings.json",
		Description: "Permissions allowlist, hooks scaffold, model defaults. Deep-merges with any existing settings.json.",
		Category:    CategorySettings,
		Conflict:    ConflictMerge,
		Files: []TargetFile{{
			Path: ".claude/settings.json",
			Mode: 0o644,
			Body: placeholderBody(
				"{\n" +
					"  \"_omc_preview\": \"placeholder — real schema lands in M6\",\n" +
					"  \"permissions\": {\n" +
					"    \"allow\": [],\n" +
					"    \"deny\": []\n" +
					"  }\n" +
					"}\n",
			),
		}},
	})

	register(Component{
		ID:          "gitignore",
		Title:       ".gitignore additions",
		Description: "Adds .claude/settings.local.json, .claude/.omc-backup-*, and .claude/omc/ to .gitignore.",
		Category:    CategoryGitignore,
		Conflict:    ConflictMerge,
		Files: []TargetFile{{
			Path: ".gitignore",
			Mode: 0o644,
			Body: placeholderBody(
				"# omc additions\n" +
					".claude/settings.local.json\n" +
					".claude/.omc-backup-*/\n" +
					".claude/omc/\n",
			),
		}},
	})

	// Format-on-save hook — applies whenever the detected Stack carries a
	// non-empty Formatter command. The hook itself execs whatever the
	// LLM declared (gofmt / prettier / ruff / …), so adding a new
	// language is zero work here: a new detector run that yields a
	// Formatter value automatically opts the project in.
	register(Component{
		ID:          "hook.format-on-save",
		Title:       "PostToolUse format-on-save hook",
		Description: "Runs the formatter declared by the detected stack after Claude writes a file. Opt-in, executable on your machine — review before applying.",
		Category:    CategoryHook,
		AppliesTo:   func(s detect.Stack) bool { return s.Formatter != "" },
		Conflict:    ConflictSkipIfExists,
		Files: []TargetFile{{
			Path: ".claude/hooks/format-on-save.sh",
			Mode: 0o755,
			Body: placeholderBody(
				"#!/usr/bin/env bash\n" +
					"# Generated by omc — runs the formatter declared by your detected stack.\n" +
					"# The real hook (M6) substitutes the formatter command at template time.\n" +
					"set -eu\n" +
					"exit 0\n",
			),
		}},
	})
}
